### ISSUE TITLE
wget.racing down

### ISSUE THREAD

**Issue by n-st** [n-st/nench#12]
The server hosting wget.racing is currently (and likely permanently) offline. A replacement is being prepared, apologies for the inconvenience.

**Comment by jaydrogers** [comment]
Thanks for looking into this!

This worked for me in the meantime:

```bash
(curl -s https://raw.githubusercontent.com/n-st/nench/master/nench.sh | bash; curl -s https://raw.githubusercontent.com/n-st/nench/master/nench.sh | bash) 2>&1 | tee nench.log
```

**Comment by n-st** [comment]
wget.racing is now available again from a new server.
It may see a few more short interruptions as I'm migrating more services to the new server, but should be usable.
